#!/usr/bin/env python3
"""Write the club's tiers from the catalogue into the landing page.

The offer page a member receives is rendered from api/app/tiers.json. The
landing page is static HTML, so without this it would be a second copy of the
same prices, free to drift — and a visitor shown $180 who is then charged $205
is a bug that costs trust rather than pixels.

This rewrites the block between the ALLOCATIONS markers in index.html and
leaves everything else alone. It is safe to run repeatedly; it makes no change
if the page already agrees with the catalogue.

Run from the repo root:  python3 tools/sync_tiers.py [--check]
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PAGE = ROOT / "index.html"
CATALOGUE = ROOT / "api" / "app" / "tiers.json"

START = "<!-- tiers:start — generated by tools/sync_tiers.py, do not edit by hand -->"
END = "<!-- tiers:end -->"


def card(tier: dict) -> str:
    classes = "tier-card"
    if tier["featured"]:
        classes += " featured"
    price = f"${tier['price_cents'] / 100:,.0f}"
    shipping = (f"per shipment &middot; +${tier['shipping_cents'] / 100:,.0f} shipping"
                if tier["shipping_cents"] else "per shipment &middot; shipping included")
    benefits = "\n".join(f"          <li>{b}</li>" for b in tier["benefits"])

    if tier["invite_only"]:
        action = '<span class="tier-cta tier-cta--locked">By Invitation</span>'
    else:
        action = (f'<a href="#join" class="tier-cta" data-tier="{tier["key"]}">'
                  f'Request This Allocation</a>')

    return f"""      <div class="{classes}">
        <p class="tier-label">{tier['label']}</p>
        <h3 class="tier-name serif">{tier['name']}</h3>
        <p class="tier-desc">{tier['summary']}</p>
        <ul class="tier-details">
{benefits}
        </ul>
        <p class="tier-price">From {price} <small>{shipping}</small></p>
        {action}
      </div>"""


def options(tiers: list[dict]) -> str:
    """The allocation select on the request form: what a visitor may ask for."""
    rows = [
        f'        <option value="{t["key"]}">{t["name"]} &mdash; '
        f'{t["bottles"]} bottles, {{n}} a year</option>'
        for t in tiers if not t["invite_only"]
    ]
    return "\n".join(rows)


def build(catalogue: dict) -> tuple[str, str]:
    per_year = {1: "once", 2: "twice", 4: "four times"}.get(
        catalogue["shipments_per_year"], f"{catalogue['shipments_per_year']} times")
    cards = "\n\n".join(card(t) for t in catalogue["tiers"])
    opts = options(catalogue["tiers"]).replace("{n}", per_year)
    return cards, opts


def main() -> int:
    check = "--check" in sys.argv
    catalogue = json.loads(CATALOGUE.read_text())
    page = PAGE.read_text()
    cards, opts = build(catalogue)

    if START not in page or END not in page:
        print(f"index.html has no {START!r} / {END!r} markers", file=sys.stderr)
        return 2

    updated = re.sub(
        re.escape(START) + r".*?" + re.escape(END),
        f"{START}\n{cards}\n      {END}",
        page, flags=re.S,
    )
    updated = re.sub(
        r'(<!-- tier-options:start -->).*?(<!-- tier-options:end -->)',
        lambda m: f"{m.group(1)}\n{opts}\n        {m.group(2)}",
        updated, flags=re.S,
    )

    if updated == page:
        print("index.html already matches the catalogue")
        return 0
    if check:
        print("index.html is out of date with api/app/tiers.json", file=sys.stderr)
        return 1

    PAGE.write_text(updated)
    print(f"index.html updated from {CATALOGUE.relative_to(ROOT)} "
          f"({len(catalogue['tiers'])} tiers)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
